version: "3"
services:
  test-mongo:
    container_name: test-mongo
    image: mongo:latest
    #restart: always
    ports:
      - 27017:27017
    networks:
      - test-network
    volumes:
      - test_mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: test
      DB_NAME: test
      DB_USER: root
      DB_PASSWORD: root

  test-mongo-express:
    container_name: test-mongo-express
    image: mongo-express:latest
    #restart: always
    depends_on:
      - test-mongo
    networks:
      - test-network
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@test-mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

networks:
  test-network:
    driver: bridge
volumes:
  test_mongodb_data:

