spring:
  application:
    name=realtime-quiz-demo:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: realtime-quiz-demo
      username: root
      password: root
      authentication-database: admin
      auto-index-creation: true

socket-server:
  port: 8085
  host: 127.0.0.1 #0.0.0.0

logging:
  level:
    root: info